import { db } from "@/lib/db";
import { generateLinkCode } from "@/lib/referralCode";
import { Prisma } from "@prisma/client";
import type { CurrencyTotal } from "@/lib/analytics";
import type { CommissionStatus } from "@/lib/commission";

// Owner-scoping is done in the query, never inferred from the route guard.
// An Affiliate reaches an Owner only through its Merchant, so both links get
// checked: the Merchant is the Owner's, and the Affiliate is that Merchant's.
async function assertMerchantOwnership(ownerId: string, merchantId: string): Promise<void> {
  const merchant = await db.merchant.findFirst({
    where: { id: merchantId, ownerId },
    select: { id: true },
  });
  if (!merchant) {
    throw new Error("Merchant not found");
  }
}

export type CreateAffiliateInput = { name: string; email: string };

function normalizeEmail(email: string): string {
  return email.trim().toLowerCase();
}

// Callers are expected to have already established that the Owner owns this
// Merchant (the dashboard reaches this only via listMerchantsForOwner), so
// this takes no ownerId and does no ownership check of its own.
export async function countAffiliatesForMerchant(merchantId: string): Promise<number> {
  return db.affiliate.count({ where: { merchantId } });
}

export async function createAffiliate(
  merchantId: string,
  programId: string,
  input: CreateAffiliateInput
): Promise<{ id: string; email: string; referralCode: string }> {
  const email = normalizeEmail(input.email);
  const code = await generateLinkCode(input.name);

  // One transaction: the code is globally unique and generated by a
  // read-then-write, so a losing race must not leave an Affiliate with no link.
  const affiliate = await db.affiliate.create({
    data: {
      merchantId,
      programId,
      email,
      name: input.name,
      links: { create: { code, isPrimary: true } },
    },
    select: { id: true, email: true },
  });

  return { id: affiliate.id, email: affiliate.email, referralCode: code };
}

export async function getAffiliateByEmail(
  merchantId: string,
  email: string
): Promise<{ id: string; email: string; referralCode: string } | null> {
  const affiliate = await db.affiliate.findUnique({
    where: { merchantId_email: { merchantId, email: normalizeEmail(email) } },
    select: { id: true, email: true, links: { where: { isPrimary: true }, select: { code: true } } },
  });
  if (!affiliate) return null;
  return {
    id: affiliate.id,
    email: affiliate.email,
    referralCode: affiliate.links[0]?.code ?? "",
  };
}

export async function getAffiliateSession(
  affiliateId: string
): Promise<{ referralCode: string; merchantWebsiteUrl: string; merchantId: string } | null> {
  const affiliate = await db.affiliate.findUnique({
    where: { id: affiliateId },
    select: {
      links: { where: { isPrimary: true }, select: { code: true, destinationPath: true } },
      merchant: { select: { id: true, websiteUrl: true } },
    },
  });
  if (!affiliate) return null;
  return {
    referralCode: affiliate.links[0]?.code ?? "",
    merchantWebsiteUrl: affiliate.merchant.websiteUrl,
    merchantId: affiliate.merchant.id,
  };
}

export type AffiliateCommissionStatus = "PENDING" | "PAYABLE" | "PAID" | "VOIDED";

const AFFILIATE_VISIBLE_STATUSES: readonly AffiliateCommissionStatus[] = [
  "PENDING",
  "PAYABLE",
  "PAID",
  "VOIDED",
];

export function toDisplayStatus(status: string): AffiliateCommissionStatus {
  return (AFFILIATE_VISIBLE_STATUSES as readonly string[]).includes(status)
    ? (status as AffiliateCommissionStatus)
    : "PENDING";
}

export type AffiliateStatusTotal = {
  currency: string;
  status: AffiliateCommissionStatus;
  amount: string;
};

export type AffiliateStats = {
  totalClicks: number;
  totals: AffiliateStatusTotal[];
};

export async function getAffiliateStats(affiliateId: string): Promise<AffiliateStats> {
  const [totalClicks, grouped] = await Promise.all([
    db.click.count({ where: { affiliateId } }),
    db.commission.groupBy({
      by: ["currency", "status"],
      where: { affiliateId },
      _sum: { amount: true },
    }),
  ]);

  const merged = new Map<string, Prisma.Decimal>();
  for (const g of grouped) {
    const status = toDisplayStatus(g.status);
    const key = `${g.currency}:${status}`;
    const amount = g._sum.amount ?? new Prisma.Decimal(0);
    merged.set(key, (merged.get(key) ?? new Prisma.Decimal(0)).add(amount));
  }

  const totals: AffiliateStatusTotal[] = [...merged.entries()].map(([key, amount]) => {
    const [currency, status] = key.split(":");
    return { currency, status: status as AffiliateCommissionStatus, amount: amount.toFixed(2) };
  });

  return { totalClicks, totals };
}

export type AffiliateCommissionRow = {
  id: string;
  amount: string;
  currency: string;
  status: AffiliateCommissionStatus;
  createdAt: Date;
  payableAt: Date;
  paidAt: Date | null;
  linkCode: string | null;
};

/**
 * A status filter as an Affiliate can express it, folded onto the real
 * `where` clause. Asking for PENDING has to also match FLAGGED, or the tile
 * that says "6 pending" and the rows behind it would disagree the moment a
 * flag exists (`toDisplayStatus` folds the same way for display).
 */
function affiliateStatusWhere(status: AffiliateCommissionStatus | null | undefined) {
  if (!status) return {};
  if (status === "PENDING") {
    return { status: { in: ["PENDING", "FLAGGED"] as CommissionStatus[] } };
  }
  return { status: status as CommissionStatus };
}

export async function listAffiliateCommissions(
  affiliateId: string,
  {
    page,
    pageSize,
    status,
  }: { page: number; pageSize: number; status?: AffiliateCommissionStatus | null }
): Promise<{ rows: AffiliateCommissionRow[]; total: number }> {
  const where = { affiliateId, ...affiliateStatusWhere(status) };
  const [rows, total] = await Promise.all([
    db.commission.findMany({
      where,
      select: {
        id: true,
        amount: true,
        currency: true,
        status: true,
        createdAt: true,
        payableAt: true,
        paidAt: true,
        click: { select: { link: { select: { code: true } } } },
      },
      orderBy: { createdAt: "desc" },
      skip: (page - 1) * pageSize,
      take: pageSize,
    }),
    db.commission.count({ where }),
  ]);

  return {
    total,
    rows: rows.map((r) => ({
      id: r.id,
      currency: r.currency,
      createdAt: r.createdAt,
      payableAt: r.payableAt,
      paidAt: r.paidAt,
      amount: r.amount.toFixed(2),
      status: toDisplayStatus(r.status),
      linkCode: r.click.link?.code ?? null,
    })),
  };
}

/**
 * Count per visible status, for the commissions screen's filter tiles.
 *
 * FLAGGED folds into PENDING here too, the same way `listAffiliateCommissions`
 * folds it in the `where`: a flag is an accusation the Merchant has not acted
 * on, and it must never surface to the Affiliate it is about, tile count
 * included.
 */
export async function getAffiliateCommissionTotals(
  affiliateId: string
): Promise<{ status: AffiliateCommissionStatus; count: number }[]> {
  const grouped = await db.commission.groupBy({
    by: ["status"],
    where: { affiliateId },
    _count: { _all: true },
  });

  const counts = new Map<AffiliateCommissionStatus, number>();
  for (const g of grouped) {
    const status = toDisplayStatus(g.status);
    counts.set(status, (counts.get(status) ?? 0) + g._count._all);
  }

  return AFFILIATE_VISIBLE_STATUSES.map((status) => ({
    status,
    count: counts.get(status) ?? 0,
  }));
}

export async function updateAffiliatePayoutDetails(
  affiliateId: string,
  payoutDetails: string
): Promise<void> {
  const trimmed = payoutDetails.trim();
  await db.affiliate.update({
    where: { id: affiliateId },
    data: { payoutDetails: trimmed || null },
  });
}

export async function getAffiliatePayoutDetails(affiliateId: string): Promise<string | null> {
  const affiliate = await db.affiliate.findUnique({
    where: { id: affiliateId },
    select: { payoutDetails: true },
  });
  return affiliate?.payoutDetails ?? null;
}

export type AffiliateListFilters = {
  /** Null means every Program on the Merchant. */
  programId: string | null;
  /** Matches a name, an email or a referral code. */
  query: string | null;
};

export type AffiliateListRow = {
  id: string;
  name: string | null;
  email: string;
  referralCode: string;
  programId: string;
  programName: string;
  programSlug: string;
  /** The override when the Affiliate has one, otherwise the Program default. */
  commissionRate: string;
  rateIsOverride: boolean;
  clicks: number;
  conversions: number;
  /** One entry per currency. Supaffi never converts (CONTEXT.md). */
  earned: CurrencyTotal[];
  createdAt: Date;
};

export const AFFILIATES_PAGE_SIZE = 25;

/**
 * Everyone promoting this product, with what they have brought in.
 *
 * This lives here rather than in analytics.ts because a row is an affiliate,
 * not a metric: identity, program and rate are the point, and the counts hang
 * off them.
 *
 * The counts are gathered in three grouped queries keyed on the ids of the
 * page that was just read, not per row and not over the whole Merchant. That
 * keeps the cost of the screen flat at five queries whether the account has
 * one affiliate or ten thousand, and it means an affiliate with no clicks
 * still comes back as a zero rather than dropping out of a join.
 */
export async function listAffiliatesForMerchant(
  ownerId: string,
  merchantId: string,
  filters: AffiliateListFilters,
  { page, pageSize }: { page: number; pageSize: number }
): Promise<{ rows: AffiliateListRow[]; total: number }> {
  await assertMerchantOwnership(ownerId, merchantId);

  const query = filters.query?.trim();
  const where = {
    merchantId,
    merchant: { ownerId },
    ...(filters.programId ? { programId: filters.programId } : {}),
    ...(query
      ? {
          OR: [
            { name: { contains: query, mode: "insensitive" as const } },
            { email: { contains: query, mode: "insensitive" as const } },
            { links: { some: { code: { contains: query, mode: "insensitive" as const } } } },
          ],
        }
      : {}),
  };

  const [total, affiliates] = await Promise.all([
    db.affiliate.count({ where }),
    db.affiliate.findMany({
      where,
      select: {
        id: true,
        name: true,
        email: true,
        links: { where: { isPrimary: true }, select: { code: true } },
        customCommissionRate: true,
        createdAt: true,
        program: {
          select: { id: true, name: true, slug: true, defaultCommissionRate: true },
        },
      },
      // Newest first. Ranking by money is the Leaderboard's job, and doing it
      // here would mean aggregating every affiliate before paging any of them.
      orderBy: { createdAt: "desc" },
      skip: (page - 1) * pageSize,
      take: pageSize,
    }),
  ]);

  if (affiliates.length === 0) return { total, rows: [] };

  const ids = affiliates.map((a) => a.id);
  const [clickCounts, conversionCounts, earnedRows] = await Promise.all([
    db.click.groupBy({
      by: ["affiliateId"],
      where: { affiliateId: { in: ids } },
      _count: { _all: true },
    }),
    // Every commission counts as a conversion, voided ones included, which is
    // what getProductMetrics counts for the rate on the same screen. Money is
    // the thing a void takes away, not the sale having happened.
    db.commission.groupBy({
      by: ["affiliateId"],
      where: { affiliateId: { in: ids } },
      _count: { _all: true },
    }),
    db.commission.groupBy({
      by: ["affiliateId", "currency"],
      where: { affiliateId: { in: ids }, status: { notIn: ["VOIDED"] } },
      _sum: { amount: true },
    }),
  ]);

  const clicksById = new Map(clickCounts.map((c) => [c.affiliateId, c._count._all]));
  const conversionsById = new Map(
    conversionCounts.map((c) => [c.affiliateId, c._count._all])
  );
  const earnedById = new Map<string, CurrencyTotal[]>();
  for (const row of earnedRows) {
    const totals = earnedById.get(row.affiliateId) ?? [];
    totals.push({
      currency: row.currency,
      total: (row._sum.amount ?? new Prisma.Decimal(0)).toFixed(2),
    });
    earnedById.set(row.affiliateId, totals);
  }

  return {
    total,
    rows: affiliates.map((a) => ({
      id: a.id,
      name: a.name,
      email: a.email,
      referralCode: a.links[0]?.code ?? "",
      programId: a.program.id,
      programName: a.program.name,
      programSlug: a.program.slug,
      commissionRate: (a.customCommissionRate ?? a.program.defaultCommissionRate).toString(),
      rateIsOverride: a.customCommissionRate !== null,
      clicks: clicksById.get(a.id) ?? 0,
      conversions: conversionsById.get(a.id) ?? 0,
      earned: (earnedById.get(a.id) ?? []).sort((x, y) =>
        x.currency.localeCompare(y.currency)
      ),
      createdAt: a.createdAt,
    })),
  };
}

export type AffiliateSignals = {
  total: number;
  /** At least one commission that has not been voided. */
  earning: number;
  joinedThisMonth: number;
};

export async function getAffiliateSignals(
  ownerId: string,
  merchantId: string
): Promise<AffiliateSignals> {
  await assertMerchantOwnership(ownerId, merchantId);

  const monthStart = new Date();
  monthStart.setUTCDate(1);
  monthStart.setUTCHours(0, 0, 0, 0);

  const scope = { merchantId, merchant: { ownerId } };
  const [total, earning, joinedThisMonth] = await Promise.all([
    db.affiliate.count({ where: scope }),
    db.affiliate.count({
      where: { ...scope, commissions: { some: { status: { not: "VOIDED" } } } },
    }),
    db.affiliate.count({ where: { ...scope, createdAt: { gte: monthStart } } }),
  ]);

  return { total, earning, joinedThisMonth };
}

export type AffiliateDetailCommission = {
  id: string;
  amount: string;
  currency: string;
  /** The real status, flags included: this is the Owner's view, not the Affiliate's. */
  status: CommissionStatus;
  createdAt: Date;
};

export type AffiliateDetail = {
  payoutDetails: string | null;
  commissions: AffiliateDetailCommission[];
};

/**
 * What the detail sheet shows that the list row does not.
 *
 * Fetched for the whole page up front rather than on click, so opening a row
 * is instant and needs no loading state. Bounded by `perAffiliate`, so the
 * cost is a page of rows times a handful of commissions, not an affiliate's
 * entire history.
 */
export async function getAffiliateDetails(
  ownerId: string,
  merchantId: string,
  affiliateIds: string[],
  perAffiliate = 8
): Promise<Record<string, AffiliateDetail>> {
  await assertMerchantOwnership(ownerId, merchantId);
  if (affiliateIds.length === 0) return {};

  const affiliates = await db.affiliate.findMany({
    where: { id: { in: affiliateIds }, merchantId, merchant: { ownerId } },
    select: {
      id: true,
      payoutDetails: true,
      commissions: {
        select: { id: true, amount: true, currency: true, status: true, createdAt: true },
        orderBy: { createdAt: "desc" },
        take: perAffiliate,
      },
    },
  });

  return Object.fromEntries(
    affiliates.map((a) => [
      a.id,
      {
        payoutDetails: a.payoutDetails,
        commissions: a.commissions.map((c) => ({
          id: c.id,
          amount: c.amount.toFixed(2),
          currency: c.currency,
          status: c.status as CommissionStatus,
          createdAt: c.createdAt,
        })),
      },
    ])
  );
}
